<option value="Accounting & Auditing">Accounting &amp; Auditing</option>
<option value="Administrative & Clerical">Administrative &amp; Clerical</option>
<option value="Advertising & Marketing">Advertising &amp; Marketing</option>
<option value="Agriculture, Forestry & Fishing">Agriculture, Forestry &amp; Fishing</option>
<option value="Architecture & Design">Architecture &amp; Design</option>
<option value="Arts & Entertainment">Arts &amp; Entertainment</option>
<option value="Automotive">Automotive</option>
<option value="Banking & Finance">Banking &amp; Finance</option>
<option value="Biotech & Pharmaceuticals">Biotech &amp; Pharmaceuticals</option>
<option value="Business Development">Business Development</option>
<option value="Construction">Construction</option>
<option value="Consulting">Consulting</option>
<option value="Customer Service">Customer Service</option>
<option value="Education">Education</option>
<option value="Engineering">Engineering</option>
<option value="Environmental">Environmental</option>
<option value="Executive">Executive</option>
<option value="Facilities">Facilities</option>
<option value="Fashion & Apparel">Fashion &amp; Apparel</option>
<option value="Food Service">Food Service</option>
<option value="Government & Military">Government &amp; Military</option>
<option value="Healthcare">Healthcare</option>
<option value="Hospitality & Tourism">Hospitality &amp; Tourism</option>
<option value="Human Resources">Human Resources</option>
<option value="Information Technology">Information Technology</option>
<option value="Insurance">Insurance</option>
<option value="Legal">Legal</option>
<option value="Management & Consulting">Management &amp; Consulting</option>
<option value="Manufacturing">Manufacturing</option>
<option value="Media & Communication">Media &amp; Communication</option>
<option value="Non-Profit & Volunteering">Non-Profit &amp; Volunteering</option>
<option value="Oil, Gas & Energy">Oil, Gas &amp; Energy</option>
<option value="Operations">Operations</option>
<option value="Other">Other</option>
<option value="Product & Project Management">Product &amp; Project Management</option>
<option value="Public Relations">Public Relations</option>
<option value="Real Estate">Real Estate</option>
<option value="Research & Development">Research &amp; Development</option>
<option value="Sales">Sales</option>
<option value="Sciences">Sciences</option>
<option value="Social Services">Social Services</option>
<option value="Sports & Fitness">Sports &amp; Fitness</option>
<option value="Supply Chain & Logistics">Supply Chain &amp; Logistics</option>
<option value="Telecommunications">Telecommunications</option>
<option value="Transportation">Transportation</option>
<option value="Travel & Tourism">Travel &amp; Tourism</option>
<option value="Web Development & Design">Web Development &amp; Design</option>
