<?php
    return [
        "Accounting & Auditing",
        "Administrative & Clerical",
        "Advertising & Marketing",
        "Agriculture, Forestry & Fishing",
        "Architecture & Design",
        "Arts & Entertainment",
        "Automotive",
        "Banking & Finance",
        "Biotech & Pharmaceuticals",
        "Business Development",
        "Construction",
        "Consulting",
        "Customer Service",
        "Education",
        "Engineering",
        "Environmental",
        "Executive",
        "Facilities",
        "Fashion & Apparel",
        "Food Service",
        "Government & Military",
        "Healthcare",
        "Hospitality & Tourism",
        "Human Resources",
        "Information Technology",
        "Insurance",
        "Legal",
        "Management & Consulting",
        "Manufacturing",
        "Media & Communication",
        "Non-Profit & Volunteering",
        "Oil, Gas & Energy",
        "Operations",
        "Other",
        "Product & Project Management",
        "Public Relations",
        "Real Estate",
        "Research & Development",
        "Sales",
        "Sciences",
        "Social Services",
        "Sports & Fitness",
        "Supply Chain & Logistics",
        "Telecommunications",
        "Transportation",
        "Travel & Tourism",
        "Web Development & Design"
    ];
